### PR TITLE
Elbrujohalcon patch 1

### PR DESCRIPTION
**Pull request by elbrujohalcon**

### CODE REVIEW

**Comment by gadgetci** [comment]
According to **Elvis**:
> Dependency 'sync' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'

**Comment by gadgetci** [comment]
According to **Elvis**:
> Dependency 'lager' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'

**Comment by gadgetci** [comment]
According to **Elvis**:
> Dependency 'eper' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'

**Comment by gadgetci** [comment]
According to **Elvis**:
> Dependency 'katana' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'

**Review by elvisci — DISMISSED** [review]
- Dependency 'sync' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
- Dependency 'lager' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
- Dependency 'eper' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
- Dependency 'katana' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'

**Review by elvisci — DISMISSED** [review]
- Dependency 'sync' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
- Dependency 'lager' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
- Dependency 'eper' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
- Dependency 'katana' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'

**Comment by elvisci** [comment]
Dependency 'sync' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'

**Comment by elvisci** [comment]
Dependency 'lager' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'

**Comment by elvisci** [comment]
Dependency 'eper' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'

**Comment by elvisci** [comment]
Dependency 'katana' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'

**Review by elvisci — APPROVED** [review]
:+1:

**Comment by elbrujohalcon** [comment]
This PR is useless now 😢

**Pull request closed without merging**
